# Generated by Django 4.2.1 on 2023-06-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0003_remove_grade_specialist_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
