# Generated by Django 4.2.1 on 2023-06-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0004_alter_grade_grade_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='hour',
            name='hour',
            field=models.IntegerField(default=0),
        ),
    ]
