# Generated by Django 4.2.1 on 2023-06-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0005_grade_cost_alter_hour_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
