# Generated by Django 4.2.1 on 2023-06-01 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sp', '0006_alter_cash_cash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.CharField(blank=True, max_length=1000, null=True)),
                ('hour', models.IntegerField(default=0)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_completion', models.DateField(blank=True, null=True)),
                ('deadline_date', models.DateField(blank=True)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
