# Generated by Django 4.2.1 on 2023-05-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department_admin',
            field=models.BooleanField(default=True),
        ),
    ]
