# Generated by Django 4.2.1 on 2023-05-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0003_remove_type_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='types',
            field=models.CharField(choices=[('E', 'Economy'), ('B', 'Business'), ('L', 'Luxury')], default='E', max_length=9),
        ),
    ]
