# Generated by Django 4.2.1 on 2023-05-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0004_type_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='sizes',
            field=models.CharField(choices=[('1', 'One-person'), ('2', 'Two-person'), ('4', 'Four-person')], default='1', max_length=9),
        ),
    ]
