# Generated by Django 4.2.1 on 2023-05-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0005_size_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='sizes',
            field=models.CharField(choices=[('1', 'One-person'), ('2', 'Two-person'), ('4', 'Four-person')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='type',
            name='types',
            field=models.CharField(choices=[('E', 'Economy'), ('B', 'Business'), ('L', 'Luxury')], default='E', max_length=50),
        ),
    ]
