# Generated by Django 4.2.1 on 2023-05-05 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='associated_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assotiated_book', to='book_review.book'),
        ),
    ]
