# Generated by Django 4.2.1 on 2023-05-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0004_rename_humbnail_url_book_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='categories',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
