# Generated by Django 4.2.1 on 2023-05-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0005_alter_book_author_alter_book_categories_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='book',
            name='avr_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='cnt_rating',
            field=models.IntegerField(default=0),
        ),
    ]
