# Generated by Django 4.2 on 2023-04-28 19:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0002_gif_likes_alter_category_gifs'),
    ]

    operations = [
        migrations.AddField(
            model_name='gif',
            name='comments',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
